apiVersion: v1
kind: Pod
metadata:
  #name: test-pod
  name: nextflow-pod
  namespace: thammphi
spec:
  containers:
    #- name: test-pod
    - name: nextflow-pod
      image: nextflow/nextflow:24.05.0-edge
      #image: ubuntu:latest
      #image: staphb/sratoolkit:3.0.7
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: thammphi-pvc
          mountPath: /data
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: usedby
                operator: In
                values:
                  - thammphi
  volumes:
    - name: thammphi-pvc
      persistentVolumeClaim:
        claimName: thammphi-pvc
