apiVersion: v1
kind: PersistentVolume
metadata:
  name: thammphi-energy-pv-hu-worker-c38
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /sys/class/powercap/intel-rapl/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - hu-worker-c38
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thammphi-energy-pvc-hu-worker-c38
  namespace: thammphi
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: thammphi-energy-pv-hu-worker-c38

---
apiVersion: v1
kind: Pod
metadata:
  name: thammphi-pod-c38
  namespace: thammphi
spec:
  nodeSelector:
    kubernetes.io/hostname: hu-worker-c38
  containers:
    - name: thammphi-pod-c38
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep infinity"]
      volumeMounts:
        - mountPath: /energy-data/node-c38
          name: energy-volume
          readOnly: true
        - mountPath: /private-data
          name: private-volume
  volumes:
    - name: energy-volume
      persistentVolumeClaim:
        claimName: thammphi-energy-pvc-hu-worker-c38
    - name: private-volume
      persistentVolumeClaim:
        claimName: thammphi-pvc